"""empty message

Revision ID: 22a490f47410
Revises: 
Create Date: 2019-12-02 21:50:44.298297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a490f47410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('songs_dances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('songs_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=150), nullable=True),
    sa.Column('color', sa.Unicode(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('songs_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=350), nullable=False),
    sa.Column('path', sa.Unicode(length=500), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('last_edit_date', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('dance_id', sa.Integer(), nullable=True),
    sa.Column('creation_user_id', sa.Integer(), nullable=True),
    sa.Column('last_edit_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['songs_artists.id'], ),
    sa.ForeignKeyConstraint(['creation_user_id'], ['users_user.id'], ),
    sa.ForeignKeyConstraint(['dance_id'], ['songs_dances.id'], ),
    sa.ForeignKeyConstraint(['last_edit_user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'dance_id', 'title')
    )
    op.create_table('songs_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Unicode(length=1000), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs_songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'song_id')
    )
    op.create_table('songs_labels_to_songs',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['songs_labels.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs_songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'label_id')
    )
    op.create_table('songs_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs_songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'song_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs_ratings')
    op.drop_table('songs_labels_to_songs')
    op.drop_table('songs_comments')
    op.drop_table('songs_songs')
    op.drop_table('users_user')
    op.drop_table('songs_labels')
    op.drop_table('songs_dances')
    op.drop_table('songs_artists')
    # ### end Alembic commands ###
