"""empty message

Revision ID: 529e44919d61
Revises: 22a490f47410
Create Date: 2019-12-02 22:00:06.792117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529e44919d61'
down_revision = '22a490f47410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs_songs', sa.Column('is_on_wishlist', sa.Boolean(), nullable=True))
    op.execute("UPDATE songs_songs SET is_on_wishlist = 0;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs_songs', 'is_on_wishlist')
    # ### end Alembic commands ###
